# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestTest():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}
        self.driver.implicitly_wait(10)

    def teardown_method(self, method):
        self.driver.quit()

    def test_test(self):
        # Test name: test
        # Step # | name | target | value | comment
        # 1 | open | /login?redirect=%2F |  |
        self.driver.get("http://192.168.16.50:10006/login?redirect=%2F")
        # 2 | setWindowSize | 2063x832 |  |
        self.driver.set_window_size(2063, 832)
        # 3 | click | name=username |  |
        self.driver.find_element(By.NAME, "username").click()
        # 4 | type | name=username | dev |
        self.driver.find_element(By.NAME, "username").send_keys("dev")
        # 5 | click | name=password |  |
        self.driver.find_element(By.NAME, "password").click()
        # 6 | type | name=password | air2021 |
        self.driver.find_element(By.NAME, "password").send_keys("air2021")
        # 7 | click | name=verifyCode |  |
        self.driver.find_element(By.NAME, "verifyCode").click()
        # 8 | type | name=verifyCode | 3w83 |
        self.driver.find_element(By.NAME, "verifyCode").send_keys("3w83")
        # 9 | click | css=.el-button |  |
        self.driver.find_element(By.CSS_SELECTOR, ".el-button").click()
        # 10 | click | css=.is-active .nest-menu:nth-child(4) span |  |
        self.driver.find_element(By.CSS_SELECTOR, ".is-active .nest-menu:nth-child(4) span").click()
        # 11 | click | css=div:nth-child(2) > .el-submenu .nest-menu:nth-child(2) span |  |
        self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) > .el-submenu .nest-menu:nth-child(2) span").click()
        # 12 | runScript | window.scrollTo(0,0) |  |
        self.driver.execute_script("window.scrollTo(0,0)")
        # 13 | click | css=div:nth-child(7) .nest-menu:nth-child(3) .el-menu-item |  |
        self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(7) .nest-menu:nth-child(3) .el-menu-item").click()
        # 14 | click | css=div:nth-child(9) .nest-menu:nth-child(1) .el-menu-item |  |
        self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(9) .nest-menu:nth-child(1) .el-menu-item").click()
        # 15 | mouseOver | css=div:nth-child(9) .nest-menu:nth-child(1) span |  |
        element = self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(9) .nest-menu:nth-child(1) span")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        # 16 | mouseOut | css=.is-active > span |  |
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        # 17 | click | css=.is-active .nest-menu:nth-child(6) .el-menu-item |  |
        self.driver.find_element(By.CSS_SELECTOR, ".is-active .nest-menu:nth-child(6) .el-menu-item").click()
        # 18 | click | css=.is-active .nest-menu:nth-child(3) span |  |
        self.driver.find_element(By.CSS_SELECTOR, ".is-active .nest-menu:nth-child(3) span").click()
        # 19 | click | css=#inquiryDetailBtns > .el-button:nth-child(1) > span |  |
        self.driver.find_element(By.CSS_SELECTOR, "#inquiryDetailBtns > .el-button:nth-child(1) > span").click()
        # 20 | click | css=.is-required .el-select .el-input__inner |  |
        self.driver.find_element(By.CSS_SELECTOR, ".is-required .el-select .el-input__inner").click()
        # 21 | click | css=.hover |  |
        self.driver.find_element(By.CSS_SELECTOR, ".hover").click()
        # 22 | click | css=.el-form-item:nth-child(2) .el-button |  |
        self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(2) .el-button").click()
        # 23 | click | css=.el-table__row:nth-child(1) > .el-table_6_column_101 > .cell |  |
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".el-table__row:nth-child(1) > .el-table_6_column_101 > .cell").click()
        # 24 | click | css=.loadingShow |  |
        self.driver.find_element(By.CSS_SELECTOR, ".loadingShow").click()
        # 25 | doubleClick | css=.loadingShow |  |
        element = self.driver.find_element(By.CSS_SELECTOR, ".loadingShow")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        # 26 | click | css=.el-form-item:nth-child(6) > .el-form-item__content > .el-input > .el-input__inner |  |
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".el-form-item:nth-child(6) > .el-form-item__content > .el-input > .el-input__inner").click()
        # 27 | type | css=.el-form-item:nth-child(6) > .el-form-item__content > .el-input > .el-input__inner | 110109 |
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".el-form-item:nth-child(6) > .el-form-item__content > .el-input > .el-input__inner").send_keys(
            "110109")
        # 28 | click | css=.el-dialog__footer:nth-child(3) .el-button--primary > span |  |
        self.driver.find_element(By.CSS_SELECTOR, ".el-dialog__footer:nth-child(3) .el-button--primary > span").click()


if __name__ == '__main__':
   pytest.main()
